### PR TITLE
Remove the unused 'casServerUrlPrefix' parameter

### LINKED ISSUE #329: SingleSignOutHandler.casServerUrlPrefix is not used
`org.jasig.cas.client.session.SingleSignOutHandler` logs a warning when `casServerUrlPrefix` is not set:

>Front Channel single sign out redirects are disabled when the 'casServerUrlPrefix' value is not set.

I think this warning is wrong, because `casServerUrlPrefix` isn't used anywhere in the code (except for throwing an exception when its null and logging the warning when its blank)

### PR DESCRIPTION
**Pull request by larsgrefer**
fixes #329

### CODE REVIEW

File: cas-client-core/src/main/java/org/jasig/cas/client/session/SingleSignOutHandler.java [hunk 1]
```diff
@@ -137,11 +127,6 @@ public synchronized void init() {
             CommonUtils.assertNotNull(this.logoutParameterName, "logoutParameterName cannot be null.");
             CommonUtils.assertNotNull(this.sessionMappingStorage, "sessionMappingStorage cannot be null.");
             CommonUtils.assertNotNull(this.relayStateParameterName, "relayStateParameterName cannot be null.");
-            CommonUtils.assertNotNull(this.casServerUrlPrefix, "casServerUrlPrefix cannot be null.");
```
Comment (larsgrefer) [inline cas-client-core/src/main/java/org/jasig/cas/client/session/SingleSignOutHandler.java]: This block here was the only read access to the `casServerUrlPrefix` parameter

**Comment by larsgrefer** [comment]
The travis build failure seems to be unrelated to my changes here.

**Comment by mmoayyed** [comment]
Thank you very much for the contribution. Keep 'em coming!
